### PR TITLE
fix: banner update + fixed card thumbnail

### PR DESCRIPTION
**Pull request by gianvitofanelli**
I updated the link in the banner under the main navigation and fixed the "Writing foundations" news card in the Community section.

### CODE REVIEW

**Comment by gianvitofanelli** [comment]
@Fupete can you merge this PR?

**Review by Fupete — CHANGES_REQUESTED** [review]
We can remove one "Notizia"-card on the community page. There are 4 of them right now... but there is space for three.

**Comment by Fupete** [comment]
Maybe we can remove the "May events" one from the group.

**Comment by gianvitofanelli** [comment]
Done @Fupete, can you merge this PR as soon as it's reviewed?

**Review by Fupete — APPROVED** [review]

**Pull request merged**
