### PR TITLE
fix: header megamenu a11y

### LINKED ISSUE #499: Next: header megamenu accessibility
a11y ⚠️ to fix: 
- main menu items must be `button`s and not `a`s, as they trigger the action to open megamenu (as in Bootstrap Italia megamenu example) and they are not links. 
  - FYI 🔴 this is an issue also on Bootstrap Italia documentation of the [header](https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/header/) @astagi 
- the first item on the megamenu is better rendered like a simple `a`, without the `ul` and `li` structure for just one item

To be fixed in #474  

cc ⚠️ 💙 @astagi we have to fix this also in Bootstrap Italia header nav documentation too, where the dropdowns and the megamenu are links and not the right buttons... 

Reviewed with Fabrizio. 
_Originally posted by @Fupete in https://github.com/italia/designers.italia.it/issues/474#issuecomment-1331900941_

### PR DESCRIPTION
**Pull request by gpeirolo**
Fixes #499

### CODE REVIEW

**Review by Fupete — COMMENTED** [review]
Just asked Fabrizio for an a11y review. For me it's ok. I will let u know tomorrow. Tx 🙏

**Comment by Fupete** [comment]
@gpeirolo forse andava prima mergiata questa del menu diviso in tre? 🤔

**Comment by Fupete** [comment]
@gpeirolo on monday we will have to check, we lost the megamenu up arrow now... c u

**Comment by gpeirolo** [comment]
@Fupete fixed here:
https://github.com/italia/designers.italia.it/pull/510

**Pull request merged**
