### PR TITLE
Feat design system component

### PR DESCRIPTION
**Pull request by gpeirolo**
Component page with tabs and 4 yaml files

### CODE REVIEW

**Comment by Fupete** [comment]
@gpeirolo there are some issues it seems deployment has failed... 
log screenshot

**Comment by gpeirolo** [comment]
@Fupete fixed it.

**Comment by gpeirolo** [comment]
@Fupete pushed an update with the three tabs and all of their content.
The only thing missing is the component preview and code.

**Comment by gpeirolo** [comment]
> @Fupete pushed an update with the three tabs and all of their content. The only thing missing is the component preview and code.

Tabs are not working in build, we're fixing them

**Pull request merged**
