### PR TITLE
Fix: Tooltip z index

### LINKED ISSUE #1038: Tooltip z-index issue on design system section.
### Does a discussion already exist on the topic you are interested in, or on a similar topic?

- [X] I verified and it doesn't exist

### What

There is a z-index issue with tooltips overlapped by design system navigation sidebar. See image. 

issue

### Why

It is a bug. 

### Context

Maybe a regression inserted by https://github.com/italia/designers.italia.it/commit/859d90506fcf934bd45b704ea9ec18533aa80176 @bfabio @Lorenzo-Pappalardo ?

### More

_No response_

### PR DESCRIPTION
**Pull request by Malay-dev**
Fixes #1038 
Added the following CSS for landscape tablet, laptop, and desktop screens
```css
.menu-column {
    z-index: 0!important;
  }
```

### CODE REVIEW

**Comment by Malay-dev** [comment]
Hey @Fupete, Please review this PR.... Thank you...

**Comment by Malay-dev** [comment]
Hey @Fupete, Please review this PR...

**Comment by Fupete** [comment]
@Malay-dev with the proposed solution we have a regression of an old problem with the back to top arrow falling under images. See the image below. 
I would prefer to increase the z-index of the tooltip and not set the menu sidebar to 0. Don't you agree? 
@bfabio what do you think? 

regression issue with back to top

**Comment by bfabio** [comment]
I think using `z-index` is problematic in general, we should not expect to have to fiddle with it, especially considering that places where it can make sense (modal dialogs? menus?) should already be handled by Bootstrap Italia.

`!important` is usually another clue that we have a problem somewhere else.

@Malay-dev  I'd try to stack without using `z-index` at all:
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_without_z-index

**Comment by Fupete** [comment]
Done a proposal for a more broad fix here: https://github.com/italia/designers.italia.it/pull/1077

**Comment by bfabio** [comment]
@Malay-dev the fix turned out to be a lot more convoluted than we anticipated, so we opted for this solution: #1077.

Regardless, thank you for your contribution.

**Pull request closed without merging**
