### PR TITLE
chore(ci): add linting to the pipeline

### LINKED ISSUE #630: Add linting to the pipeline
We need to lint and uniform the code style, and enforce that in the development process by adding eslint (end possibily other linters) to the CI.

### PR DESCRIPTION
**Pull request by bfabio**
Fix #630.

### CODE REVIEW

**Comment by Fupete** [comment]
Post-it: let's disable "prop spreading" check and see what remains in order to merge this as soon as possibile. (cc @bfabio )

**Comment by Fupete** [comment]
⚠️ @bfabio the component viewers are missing at page load. Check for example the page at `/design-system/componenti/accordion/`. Accordion BSI example is missing, it works just after a "select" interaction to choose another example...

**Comment by bfabio** [comment]
@Fupete great catch, this is exactly the sort of breakage we need to look for

**Comment by Fupete** [comment]
@bfabio I added a lint fix for the new 'express' dependency ✅
and I revert one of your fix to content-select.js useState parameters to resolve [this above](https://github.com/italia/designers.italia.it/pull/842#issuecomment-1691861173) ⚠️
Let's see the linting now... and please take a look 👓 

ps. still to watch for other possible issues...

**Comment by Fupete** [comment]
@bfabio discoveries: with `!isNaN` (original and now) the component viewer load but the lint fail (image below), but with the 'linted' `!number.isNaN` above the component viewer doesn't load on page landing... 🤔
 
lint error

ideas?

**Comment by Fupete** [comment]
@bfabio please check if also this issue https://github.com/italia/designers.italia.it/issues/725 will be resolved by this PR

**Comment by bfabio** [comment]
@Fupete @astagi ok, I think we are good. The `isNaN()` issue is a bit of a mystery to me, but I disabled the rule and added a note.

Also, I noticed that we have a misconfiguration with `prettier` so we get way less errors, as we [already had a sense of it](https://github.com/italia/designers.italia.it/pull/678#pullrequestreview-1418522971).  

(✖ 4090 problems (4057 errors, 33 warnings))

image


We'll fix that incrementally with more PRs.

**Review by astagi — APPROVED** [review]

**Pull request merged**
