### PR TITLE
Feat/Testing a full width approach without offsets

### PR DESCRIPTION
**Pull request by Fupete**
🚧 🧐 This is a sandbox-test PR, I'm trying to see a new larger angle here, something that @zetareticoli I know would love in case: to remove col-offset on highlight sections and use the viewport full width. 

Still some worries with the `g-0` approach for full-width image blocks, but maybe later we can remove that where is not needed. Let's see.

### CODE REVIEW

**Comment by Fupete** [comment]
🍩 Note for me: this PR could be useful also to revert to a classic columns approach, the modified files list is in fact an index of all the files where you need to intervene.

**Comment by Fupete** [comment]
@gpeirolo I think it is ok now. Tomorrow we will evaluate. Bye, tx for all

**Comment by Fupete** [comment]
Note for me: still some fixes to do on article detail, the kangaroo is not centered anymore

**Comment by Fupete** [comment]
@astagi @gpeirolo I think I am almost ready. Still some fixes to do to the article detail template. 

But, in the meantime, I just fixed also some console errors on the component view (unique `key`s, `class` instead of `classNames`) and the styling of the there tabs (fixed colors and padding). 
I also switched to an accessible theme for the code highlight viewer. We will do an "•it" theme soon, beta milestone.   

Note for me: we have to fix also the tabs of Bootstrap Italia sooner or later 🧐

**Comment by Fupete** [comment]
Ok, fixed also the kangaroo. I think I have finished restyling all the website without offset columns... and optimizing the layout here and there. @astagi @gpeirolo I need a review before merging 🙏 Tx.

**Review by gpeirolo — CHANGES_REQUESTED** [review]
@Fupete looks very good to me apart from a slight disalignment in the article detail page.
Once fixed it will be perfect.

screenshot-designers-italia-nnkym4tdj-dip-trasformazione-digitale vercel app-2022 12 07-14_27_46

**Comment by Fupete** [comment]
@gpeirolo tx, i will fix it later

**Comment by Fupete** [comment]
tx @gpeirolo @astagi just merged on `next`  🕺

**Pull request merged**
