### PR TITLE
feat: gatsby link component

### LINKED ISSUE #485: Next: internal links must use "<link to" (!)
We need to use `<Link to` ([reference](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/)) instead of `<a href` for internal navigation links. 

cc @astagi

### PR DESCRIPTION
**Pull request by gpeirolo**
Fixes #485

### CODE REVIEW

**Review by Fupete — APPROVED** [review]
Approved as far I can tell

**Comment by astagi** [comment]
Link component seem to work great! Just a note about link styling, a little dotted margin surrounds link elements @gpeirolo 

image

**Review by astagi — CHANGES_REQUESTED** [review]
Clarify dotted margin

**Comment by Fupete** [comment]
@astagi these borders are for debugging purposes. We have to remove them
before merging.

Il giorno gio 1 dic 2022 alle ore 00:18 Andrea Stagi <
***@***.***> ha scritto:

**Comment by gpeirolo** [comment]
@Fupete @astagi debugging borders removed. Ready to be merged.

**Pull request merged**
