### PR TITLE
feat/next-menu-2.0

### PR DESCRIPTION
**Pull request by Fupete**
**⚠️ Update 30/11:** 

this will become the new menu. 
We have found also a couple of major bugs with the navigation a11y, that we will fix before merging this feature (just added the bug label)

Was just trying the approach to separate the three main areas of the navigation. 

cc @astagi @gpeirolo

### CODE REVIEW

**Comment by Fupete** [comment]
@gpeirolo This is an altarnative main navigation splitted in three. I have prepared everything but we need to test the `a11y,  and check if we need more semantic (example: nesting the three current `<ul>`s (left, center, right) in a single parent `<ul>` structure) 🤔

**Review by gpeirolo — COMMENTED** [review]
@Fupete added a fix for the sticky menu.

**Comment by Fupete** [comment]
@gpeirolo I was thinking, was there a way to do it visually (separate the three areas of the navigation items) without splitting in three `ul`s? Could have been better for a11y?

**Comment by Fupete** [comment]
@gpeirolo 

a11y ⚠️ to fix: 
- main menu items must be `button`s and not `a`s, as they trigger the action to open megamenu (as in Bootstrap Italia examples) and they are not links. 
  - FYI 🔴 this is an issue also on Bootstrap Italia documentation of the [header](https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/header/) @astagi 
- the first item on the megamenu is better rendered like a simple `a`, without the `ul` and `li` structure for just one item

**Comment by Fupete** [comment]
@gpeirolo FYI just switched this to high priority and added you as a co-assigner to help fix the bugs.

**Pull request merged**
