### PR TITLE
chore(ci): Lighthouse warning when score decreases

### PR DESCRIPTION
**Pull request by bfabio**
See #851.

### CODE REVIEW

**Comment by Fupete** [comment]
@bfabio how can I test this? 🤔

**Comment by bfabio** [comment]
@Fupete I've already tested it. The quickest way is to merge it and revert if it the normal flow (as in: a PR that doesn't decrease Lighthouse scores) breaks.

After that, you can try and make a bad PR and see if it errors out.

**Comment by Fupete** [comment]
@bfabio Oooook. Still not sure. I am concerned about the first "Performance" score. It is quite different among PRs: 40 to 60, and this variations seems pretty independent from the changes by PRs.

**Review by Fupete — CHANGES_REQUESTED** [review]
Two notes from me: 
1. we cannot trust the "performance" score. As ascertained for the homepage, the score varies from 50 to 70 for no apparent reason. So it's fine to add a warning/block if PR decreases the lighthouse values, **but only for the other three control parameters** makes sense and can be blocking. Not for performance, unfortunately. 
2. we removed from the Vercel environment (now `build-dev`) the generation and thus availability of images in `avif` format, to speed up editing and streamline Vercel's work queue to build previews... This makes the `performance` parameter even less reliable than in the real production environment (`build`), where the format is available.

**Pull request closed without merging**
