### PR TITLE
Feat/next edit link

### LINKED ISSUE #403: Next: automation: get yaml url
Edit current page link

We need to automate the fetching of the current page's content `yaml` GitHub URL, to show on each pages a link "Propose changes to this page ✏️ ". 

cc @astagi

### PR DESCRIPTION
**Pull request by Fupete**
I use the current page data `Pagedata.seo.pathname` to resolve #403 

We can automate more using the current page location, to not rely on human-ingested data like this pathname, but I think it could work for now. Wdyt @gpeirolo @astagi ?

### CODE REVIEW

**Comment by gpeirolo** [comment]
@Fupete I understand what you have done but it seems to always point at the same page:
https://github.com/italia/designers.italia.it/blob/next/src/pages/index.yaml

Is it correct?

**Comment by Fupete** [comment]
@gpeirolo @astagi it is ready to merge now. Please do a review. I will wait until tomorrow morning to squash and merge just to let the time heal everything 👍 c u tomorrow 😌

**Review by gpeirolo — APPROVED** [review]

**Comment by astagi** [comment]
@Fupete sorry for my late response, review in progress by my side! I'll finish it tomorrow morning.

**Comment by Fupete** [comment]
Perfect, tx. I was wondering if we can use the native Gatsby "location"
instead of the "Pagedata.seo.pathname". I will make a couple of tests later
this morning.


*•*
*Daniele Tabellini*
Art & Design Director

linkedin.com/in/danieletabellini/

*A.P. Nasonero* Sede Legale: Corso Amedeo, 122
57125 — Livorno (LI)
PI 01621080496

nasonero.studio


Professione esercitata ai sensi della legge
14 gennaio 2013, n. 4 (G.U. n.22 del 26-1-2013)


Il giorno gio 1 dic 2022 alle ore 00:22 Andrea Stagi <
***@***.***> ha scritto:

**Comment by Fupete** [comment]
@gpeirolo @astagi moved to the location, I am not using anymore the handmade `pagedata.seo.pathname`. We have to pass "location" more through the tree from each page but I think will be more resilient to human errors... 

This is ready to merge for me. @astagi your call.

**Comment by Fupete** [comment]
Note for me: as soon as ready this will  fix also: https://github.com/italia/designers.italia.it/issues/404

**Pull request merged**
