### PR TITLE
Feat/design system template

### PR DESCRIPTION
**Pull request by gpeirolo**
Added template for design system indexes and navigation.

### CODE REVIEW

**Comment by Fupete** [comment]
@gpeirolo seems smooth. 

UI feat: I just try, only on desktop breakpoints, to add these CSSs to the sidebar container (as used on Bootstrap Italia docs) and it's lovely. Obiuvsly not on mobile 😁 

`position: sticky;
  top: 0;
  height: calc(100vh);
  overflow-y: auto;
`
Question: do we need the `light` background also on the container to avoid white on the left side? Maybe yes? Could be nice.

**Comment by gpeirolo** [comment]
> UI feat: I just try, only on desktop breakpoints, to add these CSSs to the sidebar container (as used on Bootstrap Italia docs) and it's lovely. Obiuvsly not on mobile 😁
> `position: sticky; top: 0; height: calc(100vh); overflow-y: auto; ` Maybe there is a more elegant solution with BI or B5 classes.

@Fupete do you want me to implement it on > 992px only?

> Question: do we need the `light` background also on the container to avoid white on the left side? Maybe yes? Could be nice.

I tried it out and it looks quite good with two caveats:

- the central column will need a bg-white class
- I think there's too much background on resultions from 1600 up
- 
Se attached screenshot.

FireShot Capture 015 - Fondamenti_ - designers-italia-patoyz19a-dip-trasformazione-digitale vercel app

**Comment by Fupete** [comment]
Yes, sticky with a scrollbar just where is the sidebar. 
I love the preview ✌️, consider that the sticky left sidebar will equilibrate the perception.

**Comment by Fupete** [comment]
@gpeirolo if you add the fixes cited via slack for me is ok to merge.

**Comment by gpeirolo** [comment]
@Fupete updated with the mods discussed in slack:
- sticky sidebar -> this doesn't work in build as it uses Bootstrasp Italia JS code (same old problem @marsanwedoo @astagi)
- light page background

Plus:
- fixed key error on cards
- addes skiplink to feedback section

Even though the sidebar doesn't stick I suggest we close this on next if everything else is ok.

**Comment by Fupete** [comment]
1️⃣ @gpeirolo I just fixed the conflict but there is a bug with the z-index. The mega menu is under the sidebar 🟡  , see the screen here:

bug image

If you fix it, we can squash and merge for me, and then open a second issue for the stickies problem (see below point 2 😭 )... 

—-----

2️⃣ @gpeirolo I just noticed that also the main sticky menu doesn't sticky, but it does on local dev... we need to address this issue with js/BI guys finally, how do we do @marsanwedoo @astagi ?? 🔴  🤔  

-------

**Comment by gpeirolo** [comment]
> 1️⃣ @gpeirolo I just fixed the conflict but there is a bug with the z-index. The mega menu is under the sidebar 🟡 , see the screen here:

Fixed.

> 2️⃣ @gpeirolo I just noticed that also the main sticky menu doesn't sticky, but it does on local dev... we need to address this issue with js/BI guys finally, how do we do @marsanwedoo @astagi ?? 🔴 🤔

Yes I detailed the error in my original comment.

**Review by Fupete — APPROVED** [review]

**Pull request merged**
