### PR TITLE
Fix/Projects

### PR DESCRIPTION
**Pull request by gianvitofanelli**
Fixed some copy in the Project section.

### CODE REVIEW

**Comment by Fupete** [comment]
@gianvitofanelli if this is an unfinished PR please convert it to draft... and add as final reviewers @bfabio , @danielaiozzo or me.

**Comment by gianvitofanelli** [comment]
It’s finished, you can push it if it works for you

**Comment by Fupete** [comment]
@bfabio up to u

**Review by bfabio — APPROVED** [review]
LGTM :+1:

Also, shoudn't we use the commas as decimal separator?

**Pull request merged**
